### PR TITLE
Symfony 2.8+ deprecates 'intention'

### PR DESCRIPTION
**Pull request by alister**
If the 'csrf_token_id' exists in options, use in preference to 'intention'

### CODE REVIEW

**Comment by zapashcanon** [comment]
Thanks. :)

**Comment by alister** [comment]
Any chance of a release?  Or issues and a milestone to clarfy when you think it would be ready to do so.

**Comment by zapashcanon** [comment]
I asked @K-Phoen about this a few weeks ago and forgot to do it. I created a 4.0.0 tag. Is it ok for you, or would you like a release too ? (I'm not familiar with composer, but I guess a tag is enough ?)

**Comment by alister** [comment]
That works - https://packagist.org/packages/kphoen/contact-bundle#4.0.0
It may also be good to deprecate use of Symfony 2.7 entirely - the tests are running with pretty much the latest versions of everthing anyway, including Symfony 3.2.1 (I'm still on 2.8 while I clean up some things, which was including this package)

**Comment by zapashcanon** [comment]
Is there a special reason to deprecate the use of Symfony 2.7 ? I had to drop support for PHP 7.0 because of 7cecde2 ; but for Symfony 2.7, as long as it works, I'd rather keep it.

**Comment by alister** [comment]
Fair enough - though I'd put 2.7 into the Travis test-matrix so it can be confirmed to work with at least ^2.7.

**Comment by zapashcanon** [comment]
I'll try to do it, see #30.

**Pull request merged**
